spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myhiber?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8088
  spring:
    mvc:
      pathmatch:
            matching-strategy: ant_path_matcher
